name: Build
on: [push, pull_request]
jobs:
  node-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12", "14", "16"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: |
          yarn workspace webcrypto-fallback build
          yarn workspace test-browser build
      - uses: actions/upload-artifact@v3
        with:
          name: test-browser
          path: packages/test-browser/dist/
