name: NPM Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  node-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" | tee -a $GITHUB_ENV
          echo "package_version=${GITHUB_REF#refs/*/v}" | tee -a $GITHUB_ENV
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set version
        run: node ./.ci/node-set-version.js --package-json package.json ${{ env.package_version }}
      - name: Get protobuf version
        run: |
          npm install -g js-yaml
          export protobuf_version="$(node util/get-protobuf-version.js)"
          echo "protobuf_version=${protobuf_version}" | tee -a $GITHUB_ENV
      - name: Setup protobuf
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.protobuf_version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
